import "./globals.css";
import type { Metadata } from "next";
import { Bellefair, Barlow_Condensed, Barlow } from "next/font/google";

const bellefair = Bellefair({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-bellefair",
    display: "swap",
});
const barlowCondensed = Barlow_Condensed({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-barlow-condensed",
    display: "swap",
});
const barlow = Barlow({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-barlow",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Space Tourism",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            className={`${bellefair.variable} ${barlowCondensed.variable} ${barlow.variable}`}
        >
            <body>{children}</body>
        </html>
    );
}
